version: "3.9"

services:
  front:
    container_name: dorivaldovalentim
    build:
      context: ./docker/8.3
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:8000
    networks:
      - nginx-proxy-manager
    restart: always

networks:
  nginx-proxy-manager:
    external: true