version: "3.9"

services:
  front:
    container_name: dorivaldovalentim
    build: .
    networks:
      - nginx-proxy-manager
    restart: always

networks:
  nginx-proxy-manager:
    external: true